const { ipcMain, app } = require('electron');
const path = require('path');
const fs = require('fs');

module.exports = function initLaunchers() {
  const file = path.join(app.getPath('userData'), 'onyx-launchers.json');
  let profiles = [];
  try {
    profiles = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch(e) {}

  ipcMain.handle('launchers:get', () => profiles);
  
  ipcMain.handle('launchers:save', (_, newProfiles) => {
    profiles = newProfiles;
    fs.writeFileSync(file, JSON.stringify(profiles, null, 2));
    return profiles;
  });

  ipcMain.handle('launchers:start', (_, id) => {
    // In a real implementation this would spawn commands using cross-env
    // or native child_process.spawn() relative to specified CWD
    console.log('Launchers: Starting profile', id);
    return true;
  });

  ipcMain.handle('launchers:stop', (_, id) => {
    // In a real implementation this would kill all processes generated by this profile ID
    console.log('Launchers: Stopping profile', id);
    return true;
  });
};
