import { useState, type ComponentType } from 'react';
import { Sparkles, Loader2, KeyRound, RotateCw } from 'lucide-react';

type AiResult = { text?: string; error?: string; usage?: { input: number; output: number } | null; cached?: boolean };

const ERROR_COPY: Record<string, string> = {
  'no-key': 'Add an Anthropic API key in Settings to enable this.',
  'sdk-missing': 'AI module is unavailable in this build.',
  'invalid-key': 'API key was rejected — check it in Settings.',
  'rate-limited': 'Anthropic is busy — try again in a moment.',
  'no-data': 'Nothing to analyze yet.',
  'no-logs': 'No log entries to analyze yet.',
  empty: 'The model returned nothing — try again.',
  failed: 'AI request failed — check your connection.',
};

// Self-contained AI action card: a trigger button + loading/result/error body.
// Gated by `configured`; the model call is always explicit (button), never polled.
export default function AiPanel({
  title,
  description,
  cta,
  icon: Icon = Sparkles,
  configured,
  run,
}: {
  title: string;
  description: string;
  cta: string;
  icon?: ComponentType<{ className?: string }>;
  configured: boolean;
  run: () => Promise<AiResult>;
}) {
  const [state, setState] = useState<{ loading: boolean; text?: string; error?: string; usage?: AiResult['usage']; cached?: boolean }>({ loading: false });

  const go = async () => {
    setState({ loading: true });
    try {
      const r = await run();
      if (r && r.text) setState({ loading: false, text: r.text, usage: r.usage, cached: r.cached });
      else setState({ loading: false, error: ERROR_COPY[r && r.error ? r.error : 'failed'] || 'AI request failed.' });
    } catch {
      setState({ loading: false, error: ERROR_COPY.failed });
    }
  };

  return (
    <div className="panel p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3 min-w-0">
          <div className="p-2 rounded-lg bg-primary/10 border border-primary/20 text-primary shrink-0" style={{ boxShadow: 'inset 0 1px 0 rgb(var(--text2)/0.06), 0 0 18px -6px rgb(var(--primary)/0.5)' }}>
            <Icon className="w-4 h-4" />
          </div>
          <div className="min-w-0">
            <h3 className="text-[13px] font-semibold text-text flex items-center gap-2">
              {title}
              <span className="text-[8px] font-mono font-bold tracking-widest text-primary bg-primary/10 border border-primary/20 px-1.5 py-0.5 rounded uppercase">AI</span>
            </h3>
            <p className="text-[11px] text-muted leading-relaxed mt-1">{description}</p>
          </div>
        </div>
        <button
          onClick={go}
          disabled={!configured || state.loading}
          title={configured ? undefined : 'Requires an Anthropic API key (Settings)'}
          className="shrink-0 px-3.5 py-2 bg-primary hover:bg-accent text-background text-[10px] font-mono font-bold tracking-widest rounded-lg transition-all shadow-[0_0_15px_var(--primary-alpha)] hover:shadow-[0_0_20px_var(--primary-alpha)] disabled:opacity-40 disabled:shadow-none flex items-center gap-2"
        >
          {state.loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : state.text ? <RotateCw className="w-3.5 h-3.5" /> : <Sparkles className="w-3.5 h-3.5" />}
          {state.loading ? 'THINKING' : state.text ? 'REGENERATE' : cta}
        </button>
      </div>

      {!configured && (
        <div className="mt-4 flex items-center gap-2 text-[10px] font-mono text-muted bg-surface2/60 border border-border rounded-lg px-3 py-2">
          <KeyRound className="w-3.5 h-3.5 shrink-0" /> Add an Anthropic API key in Settings to enable AI features.
        </div>
      )}

      {configured && state.loading && (
        <div className="mt-4 flex flex-col gap-2" aria-label="Generating">
          <div className="shimmer h-3 rounded w-[92%]" />
          <div className="shimmer h-3 rounded w-[78%]" />
          <div className="shimmer h-3 rounded w-[85%]" />
        </div>
      )}

      {state.error && (
        <div className="mt-4 text-[11px] font-mono text-warning bg-warning/10 border border-warning/20 rounded-lg px-3 py-2.5">
          {state.error}
        </div>
      )}

      {state.text && !state.loading && (
        <div className="mt-4 animate-in fade-in slide-in-from-bottom-1 duration-200">
          <div className="text-[12px] text-text/90 leading-relaxed whitespace-pre-wrap bg-background/50 border border-border rounded-lg p-4">
            {state.text}
          </div>
          <div className="mt-2 flex items-center justify-between text-[9px] font-mono text-muted/70">
            <span className="flex items-center gap-1.5"><Sparkles className="w-3 h-3 text-primary/60" /> Generated by Claude{state.cached ? ' · cached' : ''}</span>
            {state.usage && <span>~{state.usage.input + state.usage.output} tokens</span>}
          </div>
        </div>
      )}
    </div>
  );
}
