#!/usr/bin/env node
// One-time: generate the Onyx plugin-signing key pair (Ed25519).
//
//   node infra/plugin-signing/keygen.js
//
// Writes:
//   infra/plugin-signing/onyx-plugin-private.pem  <- SECRET. gitignored (*.pem). NEVER commit/share.
//   packages/core/src/plugins/public-key.js       <- public key. COMMIT this; it ships in the app.
//
// The private key is what proves a plugin was approved by you. Keep it offline (a
// password manager / encrypted backup). If it ever leaks, anyone can sign malicious
// plugins the app will trust — rotate by deleting the .pem, re-running this, and
// shipping a new build with the new public key.

const fs = require('fs');
const path = require('path');
const { generateKeyPair } = require('../../packages/core/src/plugins/verify');

const privPath = path.join(__dirname, 'onyx-plugin-private.pem');
const pubModulePath = path.join(__dirname, '../../packages/core/src/plugins/public-key.js');

if (fs.existsSync(privPath)) {
  console.error('Refusing to overwrite an existing private key:\n  ' + privPath +
    '\nDelete it by hand first if you really mean to rotate the key.');
  process.exit(1);
}

const { publicKey, privateKey } = generateKeyPair();
fs.writeFileSync(privPath, privateKey, { mode: 0o600 });

const moduleSrc = `// Onyx plugin-signing PUBLIC key (Ed25519, SPKI PEM). GENERATED by
// infra/plugin-signing/keygen.js — do not edit by hand. The matching PRIVATE key is
// gitignored (*.pem) and never committed. While empty, verification FAILS CLOSED.
module.exports = { ONYX_PLUGIN_PUBLIC_KEY: ${JSON.stringify(publicKey)} };
`;
fs.writeFileSync(pubModulePath, moduleSrc);

console.log('✓ Private key written (gitignored): ' + privPath);
console.log('✓ Public key written (commit this):  ' + pubModulePath);
console.log('\nNEXT: keep the private key safe & offline. Commit ONLY public-key.js.');
