// Onyx plugin-signing PUBLIC key (Ed25519, SPKI PEM). GENERATED by
// infra/plugin-signing/keygen.js — do not edit by hand. The matching PRIVATE key is
// gitignored (*.pem) and never committed. While empty, verification FAILS CLOSED.
module.exports = { ONYX_PLUGIN_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEALlfX1EC7dGs7PSPEIqm2GUF/hb0OSeC9iYFusD5WuXo=\n-----END PUBLIC KEY-----\n" };
